Update 01-email-system.md (Delivery, Retrieval, grammar...)
rocky-linux/documentation pull request #1320
Opened 2023-07-03 19:15 UTC by SergeCroise

- Delivery Agent, Retrieval Agent, see https://en.wikipedia.org/wiki/Email_agent_(infrastructure)
- grammar: an email send ... the email will be stored ... (singular)

#### Author checklist (Completed by original Author)
- [ ] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [ ] If applicable, steps and instructions have been tested to work
- [ ] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

2023-07-03 19:16 UTC, SergeCroise commented
Hello @jimcat8 and @wsoyinka ,
please review!

2023-07-04 03:24 UTC, jimcat8 requested changes
!!! question

    Why is DNS required to participate in the work of the email system?

2023-07-04 11:52 UTC, sspencerwire approved these changes

2023-07-05 03:33 UTC, jimcat8 approved these changes

2023-07-05 03:33 UTC, jimcat8 commented on docs/guides/email/01-email-system.md
>      In daily use, the standard format for an email user is "username@domain name". A domain name cannot represent a specific host, you need to point the domain name to a specific host name, so we nee
```suggestion
!!! question "Question"
    
    "Why is DNS required to participate in the work of the email system?"
    In daily use, the standard format for an email user is "username@domain name". A domain name cannot represent a specific host, you need to point the domain name to a specific host name, so we need a DNS MX resolution record.
```

2023-07-06 21:34 UTC, wsoyinka approved these changes

2023-07-06 21:34 UTC, wsoyinka commented
Thank you @SergeCroise

2023-07-06 21:34 UTC, merged