NFS server edits:
rocky-linux/documentation pull request #1342
Opened 2023-07-10 12:16 UTC by sspencerwire

* remove most (not all) passive voice
* remove punctuation on bullet points except those under "Case studies" which are a command parameters with a qualifying sentence.
* some minor wording changes for better understanding (for instance "conserved" becomes "preserves")
* added Serge to contributors

#### Author checklist (Completed by original Author)
- [ ] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [ ] If applicable, steps and instructions have been tested to work
- [ ] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

2023-07-10 12:24 UTC, sspencerwire commented
@SergeCroise @alemorvan Please review this. This is the NFS server document with some edits. See commit message for details and then review the content. Feel free to suggest changes as needed.

2023-07-10 21:22 UTC, SergeCroise requested changes

2023-07-10 21:22 UTC, SergeCroise commented on docs/guides/file_sharing/nfsserver.md
> +To force the use of a UID or GID other than that of the user writing the resource, specify the `anonuid=UID` and `anongid=GID` options, or give `anonymous` access to the data with the `all squash` op
```suggestion
To force the use of a UID or GID other than that of the user writing the resource, specify the `anonuid=UID` and `anongid=GID` options, or give `anonymous` access to the data with the `all_squash` option.
```

2023-07-11 22:29 UTC, SergeCroise approved these changes

2023-07-12 13:02 UTC, merged