Add style description
rocky-linux/documentation pull request #1822
Opened 2024-02-23 08:03 UTC by jimcat8

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

2024-02-24 16:12 UTC, SergeCroise commented on docs/books/bash_programming/01-Shell-overview.md
> +    * Bash (GNU Bourne-Again Shell, /bin/bash) - Born in 1987, it is the product of the GNU Project. Most GNU/Linux operating systems use bash as their default shell. For more detailed information, p
```suggestion
    * Bash (GNU Bourne-Again Shell, /bin/bash) - Born in 1987, it is the product of the GNU Project. Most GNU/Linux operating systems use bash as their default shell. For more detailed information, please [read this manual](https://www.gnu.org/software/bash/manual/bash.html).
```

2024-02-24 16:27 UTC, SergeCroise reviewed
hi @jimcat8 ,
Feel free to overwrite or reverse my modifications.

2024-03-09 14:59 UTC, wsoyinka requested changes

2024-03-09 14:59 UTC, wsoyinka commented on docs/books/bash_programming/01-Shell-overview.md
> +* Translators should translate the annotations on the command.
@jimcat8  - Who are notes like these ^^^ meant for ? 

I could be mistaken but -  if they are meant for translators or editors or other contributors then they don't belong directly in this book/guide/doc.  
And if the notes are meant as a form of reminder to yourself to do something later on - please convert this to work into a draft.

2024-03-09 14:59 UTC, wsoyinka commented on docs/books/bash_programming/01-Shell-overview.md
> +* Sometimes, in order to better illustrate the author's intended meaning, adjustments can be made to the output content, such as:
@jimcat8  - Who are notes like these ^^^ meant for ? 

I could be mistaken but -  if they are meant for translators or editors or other contributors then they don't belong directly in this book/guide/doc.  
And if the notes are meant as a form of reminder to yourself to do something later on - please convert this to work into a draft.

2024-03-09 14:59 UTC, wsoyinka commented on docs/books/bash_programming/01-Shell-overview.md
> +* If you want to explain a part of the output content, please add line numbers to the output using pipeline symbols.
@jimcat8  - Who are notes like these ^^^ meant for ? 

I could be mistaken but -  if they are meant for translators or editors or other contributors then they don't belong directly in this book/guide/doc.  
And if the notes are meant as a form of reminder to yourself to do something later on - please convert this to work into a draft.

2024-03-09 14:59 UTC, wsoyinka commented on docs/books/bash_programming/01-Shell-overview.md
> +* If the output content of the command is too much, the author will use "..." to indicate it.
@jimcat8  - Who are notes like these ^^^ meant for ? 

I could be mistaken but -  if they are meant for translators or editors or other contributors then they don't belong directly in this book/guide/doc.  
And if the notes are meant as a form of reminder to yourself to do something later on - please convert this to work into a draft.

2024-03-09 14:59 UTC, wsoyinka commented on docs/books/bash_programming/01-Shell-overview.md
> +* Use arrows to illustrate the meaning of command output.
@jimcat8  - Who are notes like these ^^^ meant for ? 

I could be mistaken but -  if they are meant for translators or editors or other contributors then they don't belong directly in this book/guide/doc.  
And if the notes are meant as a form of reminder to yourself to do something later on - please convert this to work into a draft.

2024-05-05 09:07 UTC, closed without merging