Zh cn
rocky-linux/documentation pull request #222
Opened 2021-08-07 10:03 UTC by wupz-repo

## Author checklist (to be completed by original Author)
- [ ] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

2021-08-07 10:03 UTC, wupz-repo commented
zh_CN

2021-08-09 19:15 UTC, calderds commented
Looks good! If you can get another Chinese speaker to read over it for accuracy, that would be great! Otherwise, leave a comment when you're ready to merge

2021-08-14 13:18 UTC, bobby285271 requested changes
You should NOT modify the original content directly. Consider create new files with translated content instead. Also, will be great if you can follow [Chinese copywriting guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md) when translating, and try to do the translation as idiomatically as possible. I will further review this later.

这个仓库不仅仅面向中文使用者的，请不要直接将英文内容直接*替换*为中文。我晚点再仔细看看翻译后的内容。

2021-08-15 04:09 UTC, bobby285271 reviewed
The following suggestions are based on my personal habits.

一些建议糅杂了我个人的翻译偏好，仅供参考。

2021-08-15 04:09 UTC, bobby285271 commented on docs-style-guide/README.md
> +也被称为连环逗号。喜欢它，使用它，并且 [查阅资料](https://en.wikipedia.org/wiki/Serial_comma) 如果你想。
```suggestion
也被称为连环逗号。尝试接纳并使用它，你可以在 [这里](https://en.wikipedia.org/wiki/Serial_comma) 查阅到相关的资料。
```

2021-08-15 04:09 UTC, bobby285271 commented on docs-style-guide/README.md
> +在任何文章中第一次提到一个软件包时，用斜体字表示，例如_rsnapshot_。特定的文件和文件夹 (eg _/home/[user]_) 应该总是用斜体字。当然，你可以在必要时使用斜体和粗体字来强调，但要少用。如果所有的东西都做成粗体字，那么文字的粗体就完全失去了它的影响力。
```suggestion
在任何文章中第一次提到一个软件包时，用斜体字表示，例如 _rsnapshot_。特定的文件和文件夹（例如 _/home/[user]_）应该总是用斜体字。当然，你可以在必要时使用斜体和粗体字来强调，但要少用。如果所有的东西都做成粗体字，那么文字的粗体就完全失去了它的作用。
```

2021-08-15 04:09 UTC, bobby285271 commented on docs-style-guide/README.md
> +一些提示可以帮助你为教程制作最好的图片。
```suggestion
希望下面这些提示可以帮助你为教程提供更优质的配图。
```

2021-08-15 04:09 UTC, bobby285271 commented on docs-style-guide/README.md
> +* 图片的推荐格式是JPG。
```suggestion
* 图片的推荐格式是 JPG。
```

2021-08-15 04:09 UTC, bobby285271 commented on docs-style-guide/README.md
> +* 如果你的截图中有很多事情发生，考虑添加几个有用的箭头，指向重要的事情。
```suggestion
* 如果你的截图包含的信息很多，考虑添加几个有用的箭头，指向重要的内容。
```

2021-08-15 04:09 UTC, bobby285271 commented on docs-style-guide/README.md
> +* 终端命令最好放在 "代码 "元素或块中。如果你必须对你的终端进行截图，请确保文本足够大，以便人们在不放大的情况下容易看到。
```suggestion
* 终端命令最好放在 `代码` 元素或块中。如果你必须对你的终端进行截图，请确保文本足够大，以便人们在不放大的情况下容易看到。
```

2021-08-15 04:13 UTC, bobby285271 commented on docs/index.md
> +# 目录
This file is already translated in #213, help improve [the existing one](https://github.com/rocky-linux/documentation/blob/main/docs/index.zh_CN.md) instead :-)

2021-08-22 17:32 UTC, closed without merging