Update index.zh_CN.md
rocky-linux/documentation pull request #230
Opened 2021-08-22 17:40 UTC by wupz-repo

## Author checklist (to be completed by original Author)
- [ ] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

2021-08-23 02:11 UTC, bobby285271 requested changes
This is obviously NOT an improvement of the existing one :-)

Will be great if you can withdrawn this PR and open another one when you are ready.

2021-08-23 02:11 UTC, bobby285271 commented on docs/index.zh_CN.md
> +| 管理员                                    | 安全                               | 一般                                           |
Why "一般"? Is this translated by machine?

2021-08-23 02:11 UTC, bobby285271 commented on docs/index.zh_CN.md
> +你发现有什么遗漏吗？你是否发现了一个错误？你是否想知道如何创建一个属于你自己的文件，或者如何解决这里的问题？还记得我们说过，*你*是洛基社区吗？那么，这意味着*你*对我们很重要，我们希望你能加入我们，如果你愿意的话，并帮助使这个文档变得更好。如果你对此感兴趣，请到我们的[贡献指南](https://github.com/rocky-linux/documentation/blob/main/RE
Maybe don't translate the word *Rocky* and leave it as is.

2021-08-23 02:11 UTC, bobby285271 commented on docs/index.zh_CN.md
> +| | [Generating SSL Keys and LetsEncrypt](guides/generating_ssl_keys_lets_encrypt.md) ||
Why are you converting this back to English?

2021-09-21 15:48 UTC, justasojourner commented
Hi @wupz-repo 

You may have seen that there has been discussion on the landing page for the documentation site. It was a TOC style document but has been changed to a more informational, how-to-use the site sort of document.

It has been great that you (and those working with you if any) have been maintaining the landing page in Simplified Chinese, I'm sure I speak for @sspencerwire and others in thanking you for that.

It would be great if you were able to undertake the translation of the new style home page 😄 

Also, on a technical note, I believe you are using a Windows machine, when you do a PR with the updated document `index.zh_CN.md` you *may* notice that there is now a process to convert Windows line endings [CR/LF] to [LF]. This document has information about this if you are interested to read:

https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

Anyway you should not even notice anything as it should be automatic.

Thanks in advance for your help in translating the new home page!

2021-09-27 16:43 UTC, sspencerwire commented
@wupz-repo Due to the new layout changes, your PR here and the work that you've done, is unfortunately no longer valid. I apologize for this. We had been working trying to figure out the best way to deal with the Table Of Contents (TOC) section of the website and finally came to the conclusion that until a better method of generating and maintaining the TOC could be found, that we were going to replace it in favor of a landing page. This was in the works when your PR was created.

We **DO** appreciate the time and effort that you've put into this and hope that you will consider doing more in the future. We are in need of your translation skills!

Thanks again for your work!!

2021-09-27 16:43 UTC, closed without merging