WIP: admin-guide - chapter 8 - process
rocky-linux/documentation pull request #95
Opened 2021-06-04 21:01 UTC by alemorvan

## Author checklist (to be completed by original Author)
- [ ] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

2021-06-04 21:02 UTC, alemorvan commented
@sspencerwire Next chapter is ready

2021-06-06 19:21 UTC, SergeCroise requested changes

2021-06-06 19:21 UTC, SergeCroise commented on en/rocky/8/admin_guide/08-process.md
> +* ready: waiting for the availability of the process ;
... process;

2021-06-06 19:21 UTC, SergeCroise commented on en/rocky/8/admin_guide/08-process.md
> +* dead : the father of the process kills his son.
dead: ...

2021-06-06 19:21 UTC, SergeCroise commented on en/rocky/8/admin_guide/08-process.md
> +The processes are classified by priority whose value varies from **-20** (the highest priority) to **+20** (the lowest priority).
... to **+19** (the lowest priority).

2021-06-06 19:21 UTC, SergeCroise commented on en/rocky/8/admin_guide/08-process.md
> +| `19` | _SIGSTOP_ | Suspending the process                                 |
Suspend the process

2021-06-06 19:21 UTC, SergeCroise commented on en/rocky/8/admin_guide/08-process.md
> +`nohup` allows to launch a process independent of a connection.
independently

2021-06-06 19:21 UTC, SergeCroise commented on en/rocky/8/admin_guide/08-process.md
> +| Colonne   | Description           |
Column

2021-06-07 06:39 UTC, SergeCroise requested changes

2021-06-07 06:39 UTC, SergeCroise commented on en/rocky/8/admin_guide/08-process.md
> +| Colonne  |  Description                |
Column

2021-06-07 16:23 UTC, sspencerwire commented
Will be merging into rl_administrator_docs, and then adding in SergeCroise editing suggestions before doing my own editing passes.

2021-06-07 16:23 UTC, merged